/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercises09;

import org.junit.Test;

import java.util.stream.IntStream;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class HistogramTest {

    //---For performance test: See drawio.HistogramComparison ---------

    //----Functional/Correctness tests---------------

    //Correctness test.
    // Specification of increment. No increment is lost. Sum = # of calls to increment
    // Pre-condition: h.bin(x) has some value k
    // Post-condition: h.bin(x) has value k+1
    @Test
    public void allHistogramsHasSameResult() {
        //Arrange
        final int range = 10000;
        final int span = 30;
        final int threadCount = 32;

        var concurrentTestRunner = new ConcurrentTestRunner(threadCount);

        var monitorHistogram = new MonitorHistogram(span, 0);
        var casHistogram = new CasHistogram(span, 0);
        var lockStripedHistogram = new LockStripedHistogram(span, 0);
        var actorHistogram = new ActorHistogram(span, 0);
        //Act
        try {
            concurrentTestRunner.runConcurrently(() -> {
                for (int j = 0; j < range; j++) {
                    monitorHistogram.increment(monitorHistogram.countFactors(j));
                    casHistogram.increment(casHistogram.countFactors(j));
                    lockStripedHistogram.increment(lockStripedHistogram.countFactors(j));
                    actorHistogram.increment(actorHistogram.countFactors(j));
                }
            });
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        //Assert
        int monitorSum = IntStream.range(0, span).map(monitorHistogram::getCount).sum();
        int casSum = IntStream.range(0, span).map(casHistogram::getCount).sum();
        int lockSum = IntStream.range(0, span).map(lockStripedHistogram::getCount).sum();
        int actorSum = IntStream.range(0, span).map(actorHistogram::getCount).sum();
        final int knownExpectedSum = threadCount * range;
        assertEquals(knownExpectedSum, monitorSum);
        assertEquals(knownExpectedSum, casSum);
        assertEquals(knownExpectedSum, lockSum);
        assertEquals(knownExpectedSum, actorSum);
    }


}
