/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercises09;

import exercises09.ExamShowcase.CustomBarrier;
import exercises09.ExamShowcase.ReadWriteHistogram;
import org.junit.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class ReadWriteHistogramTest {

    @Test
    // Specification of increment. No increment is lost. Sum = # of calls to increment
    // Pre-condition: h.bin(x) has some value k
    // Post-condition: h.bin(x) has value k+1
    public void readWriteHistogramNoIncrementsLost() {
        //Arrange
        final int range = 10000;
        final int span = 30;
        int readerThreads = 100;
        int writerThreads = 20;
        int threadCount = readerThreads + writerThreads;
        var histogram = new ReadWriteHistogram(span);

        //+1 = gate to make them start at same time.
        var startLine = new CustomBarrier(threadCount + 1);
        var finishLine = new CustomBarrier(threadCount + 1);
        //Act
        //Ready writers
        for (int i = 0; i < writerThreads; i++) {
            new Thread(() -> {
                try {
                    startLine.await();
                    for (int j = 0; j < range; j++) {
                        histogram.increment(histogram.countFactors(j));
                    }
                    finishLine.await();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }).start();
        }
        //Ready readers
        for (int i = 0; i < readerThreads; i++) {
            new Thread(() -> {
                try {
                    startLine.await();
                    for (int j = 0; j < range; j++) {
                        histogram.getTotal();
                    }
                    finishLine.await();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }).start();
        }
        try {
            startLine.await(); //start
            finishLine.await(); //Acts like join(). Wait for all threads to finish their work
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

        //Assert
        int sum = histogram.getTotal();
        final int knownExpectedSum = range*writerThreads;
        assertEquals(knownExpectedSum, sum);
    }
}
